### ISSUE TITLE
Distributed training

### ISSUE THREAD

**Issue by tymor22** [flatironinstitute/deepblast#108]
Running into the following error when setting up distribution training with Pytorch ligthing. Instances in the code (in nw_cuda.py) where we set data to device (I️.e. cuda) leads to different devices being used during distributed training.

The code used to reproduce this error message can be found at https://github.com/mortonjt/deepblast/pull/1

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
Traceback (most recent call last):
  File "deepblast_train2.py", line 66, in <module>
    trainer.fit(model)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit
    self._call_and_handle_interrupt(
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
    self._dispatch()
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in run_stage
    return self._run_train()
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1304, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1368, in _run_sanity_check
    self._evaluation_loop.run()
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 109, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 123, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 215, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 444, in validation_step
    return self.model(*args, **kwargs)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 92, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/mnt/home/thamamsy/projects/deep_blast_pull/deepblast/deepblast/trainer.py", line 240, in validation_step
    predA, theta, gap = self.aligner(seq, order)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/home/thamamsy/projects/deep_blast_pull/deepblast/deepblast/alignment.py", line 80, in forward
    zx, gx = self.blosum_factor(hx)
  File "/mnt/home/thamamsy/projects/deep_blast_pull/deepblast/deepblast/alignment.py", line 58, in blosum_factor
    hx = self.lm.encode(x)
  File "/mnt/home/thamamsy/projects/deep_blast_pull/deepblast/deepblast/language_model.py", line 340, in encode
    results = self.model(x, repr_layers=[self.layers],
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/esm/model/esm2.py", line 84, in forward
    x = self.embed_scale * self.embed_tokens(tokens)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/mnt/home/thamamsy/software/conda/envs/huggingface_meta/lib/python3.8/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:3! (when checking argument for argument index in method wrapper__index_select)
srun: error: workergpu115: task 2: Exited with exit code 1
srun: error: workergpu115: task 1: Exited with exit code 1
```

**Comment by blackwer** [comment]
I'm able to reproduce this with my own environment. I think I found the very likely cause of the bug, `deepblast/language_model.py:320:322`

```python
        self.model, self.alphabet = eval(f'esm.pretrained.{model_type}()')
        # TODO : assumes GPU is available
        self.model = self.model.eval().cuda()
```

This sets the ESM model into cuda mode, but does not specify the device. `ESM.eval().cuda(device_no)` is probably what you want. When running the code the complaint is always that there is some issue moving data between device `0` and device `[1-3]`, indicating that something is defaulting to the 0th device. I'm not sure how lightning is telling torch what device to use, but whatever mechanism it's using there, should be passed onto the constructor for the ESM2 module and then into the cuda initializer. I'll look around for an obvious way to do it, but if y'all have any insight, please let me know.

**Comment by mortonjt** [comment]
@tymor22 do you want to try getting rid of the `cuda()` call first?

**Comment by blackwer** [comment]
Nope :). I'll snoop around and see if I can scoop up the device ID in a non-hackish (or hackish, if that fails) way.
``` Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:2!```

**Comment by blackwer** [comment]
I've made some progress by overriding the `.to()` method on several classes to properly move class members to the appropriate device as well. Now for some reason it's using `numba` instead of `cuda` for NeedlemanWunsch in some spots and crashing out because of that, but I'll figure that out later today.

**Comment by blackwer** [comment]
This is actually still broken. The `ModelCheckpoint` doesn't recognize the key `validation_loss`. But it successfully runs up to that point

**Comment by mortonjt** [comment]
Thanks! Not sure what is going on with the `validation_loss`, we'll need to look into that.

**Comment by blackwer** [comment]
@mortonjt I think I fixed the `validation_loss` issue. I also got rid of some `matplotlib` nagging. You should check it out and make sure on the `esm` branch. I thought I made some progress with the ```    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
``` issue, but it's not clear. This happens sometimes when stuff ends up on the wrong `cuda` context, but I haven't figured out to debug exactly where that's happening yet.
