### ISSUE TITLE
mat1 and mat2 must have the same dtype

### ISSUE THREAD

**Issue by QUEST2179** [flatironinstitute/deepblast#140]
Follow Aligning proteins wiki

Traceback (most recent call last):
  File "C:\Users\work\project\structure\deepblast-master\testDeepBlast.py", line 19, in <module>
    pred_alignment = model.align(x, y)
  File "C:\Users\work\project\structure\deepblast-master\deepblast\trainer.py", line 84, in align
    decoded, _ = next(gen)
  File "C:\Users\work\project\structure\deepblast-master\deepblast\alignment.py", line 160, in traceback
    zx, gx = self.blosum_factor(hx)
  File "C:\Users\work\project\structure\deepblast-master\deepblast\alignment.py", line 95, in blosum_factor
    zx = self.match_embedding(hx)
  File "C:\Users\miniconda3\envs\torch10\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\work\project\structure\deepblast-master\deepblast\embedding.py", line 157, in forward
    h = self.embed(x)
  File "C:\Users\miniconda3\envs\torch10\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\miniconda3\envs\torch10\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype

**Comment by mortonjt** [comment]
Hi I havent tested this on windows, so I cant comment here. Id also double
check if your model / data are on the gpu.
